name: Ignored Rust Tests
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: ignored tests
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: IronCoreLabs/rust-toolchain@v1

      # Caching for Rust files. Must be called after installing Rust toolchain.
      # See https://github.com/Swatinem/rust-cache for more information.
      - name: Set Up Cache
        uses: Swatinem/rust-cache@v2

      - name: Run ignored tests (only!)
        run: cargo test --release -- --ignored
