name: Rust CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: ci
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        # This uses the version specified in rust-toolchain.toml by default
        uses: IronCoreLabs/rust-toolchain@v1
        with:
          components: clippy, rust-docs

      - name: Install nightly toolchain (for rustfmt only)
        run: rustup toolchain install nightly --profile minimal --component rustfmt

      - name: Install cargo-make (fast!)
        uses: davidB/rust-cargo-make@v1

      # Caching for Rust files. Must be called after installing Rust toolchain.
      # See https://github.com/Swatinem/rust-cache for more information.
      - name: Cache Rust files
        uses: Swatinem/rust-cache@v2

      - name: Run full CI (fmt, clippy, build, test, doctest, docs)
        run: cargo make ci

  deny-check:
    name: cargo-deny check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EmbarkStudios/cargo-deny-action@v1
