name: Rust CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: ci
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        id: install-rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          # Set Rust version here!
          toolchain: 1.70
          override: true
          components: rustfmt, clippy

      - name: Install nightly toolchain
        id: install-rust-nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rustfmt

      # Caching for Rust files. Must be called after installing Rust toolchain.
      # See https://github.com/Swatinem/rust-cache for more information.
      - name: Set Up Cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make

      - name: Run full CI (fmt, clippy, build, test, doctest, docs)
        run: cargo make ci

  deny-check:
    name: cargo-deny check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EmbarkStudios/cargo-deny-action@v1
